eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: service-hi
  data:
    mongodb:
      host: 192.168.1.111
      port: 22771
      database: feature_service
      username: feature_service
      password: feature_20180720